version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - princetonpy_postgres_prod:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db
  web:
    image: ghcr.io/pugip/princetonpy.org/web:release
    command: hypercorn princetonpy.asgi:application --bind 0.0.0.0:8000
    volumes:
      - princetonpy_prod_backup:/prod_backup
    expose:
      - 8000
    environment:
      - UID=1001
      - GID=1001
    env_file:
      - .env.prod.web
      - .env.prod.aws
    depends_on:
      - db
  cron:
    image: ghcr.io/pugip/princetonpy.org/cron:release
    command: yacron -c /home/app/web/crontab.yaml
    volumes:
      - princetonpy_prod_backup:/prod_backup
    environment:
      - UID=1001
      - GID=1001
    env_file:
      - .env.prod.web
      - .env.prod.aws
    depends_on:
      - web

volumes:
  princetonpy_postgres_prod:
    external: true
  princetonpy_prod_backup:
    external: true
