version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - princetonpy_postgres_prod:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: hypercorn princetonpy.asgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app:/home/app/web
      - princetonpy_static:/home/app/web/static
      - ../prod_backup:/prod_backup
    expose:
      - 8000
    env_file:
      - .env.prod.web
      - .env.prod.aws
    depends_on:
      - db
  caddy:
    image: caddy
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - princetonpy_static:/princetonpy_static
      - ./caddy/srv:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  princetonpy_postgres_prod:
    external: true
  princetonpy_static:
    external: true
  caddy_data:
    external: true
  caddy_config:
