jobs:
  - name: submit-newsletter
    command: python manage.py submit_newsletter
    schedule: "*/5 * * * *"
  - name: backup-users
    command: >-
      echo 'from princetonpy.cron.backup import *; save_users()'
      | python manage.py shell
    environment:
      - key: PYTHONPATH
        value: /home/app/web
    schedule: "0 0 * * *"
